version: '3.4'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000' # houve um ajuste aqui
    volumes:
      - .:/app
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data/
  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
    depends_on:
      - db